name: Android CI + Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Decode keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE }}" | base64 --decode > app/my-release-key.jks
          ls -la app/ 

      - name: Create local.properties for signing
        run: |
          cat > local.properties << EOF
          STORE_FILE=my-release-key.jks
          STORE_PASSWORD=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}
          KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}
          EOF
          cat local.properties # Para verificar o conteúdo
      
      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Rename APK with version
        run: |
          VERSION_NAME=${GITHUB_REF#refs/tags/}
          mv app/build/outputs/apk/release/app-release-unsigned.apk app-${VERSION_NAME}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: app-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
